global:
  scrape_interval: 6s

scrape_configs:
  - job_name: "05-api-gestao-vagas"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["172.17.0.1:8080"]
        labels:
          application: "05-api-gestao-vagas"